merge dream.N
barumau/panlexia pull request #1
Opened 2024-10-16 00:31 UTC by severin31

Is my first commit correct ? I tried to merge the two rows with dream.N

2024-10-16 16:24 UTC, barumau requested changes

2024-10-16 16:24 UTC, barumau commented on data/master.tsv
> +Body:dream.N	Body:dream.N	Successions of images, ideas, emotions, and sensations that occur usually involuntarily in the mind during certain stages of sleep.	2374		Traum::N	662
Please assign this to the meaning field Mind: `Mind:dream.N`.

2024-10-18 02:55 UTC, severin31 reviewed
Done

2024-10-18 05:41 UTC, barumau approved these changes

2024-10-18 05:41 UTC, merged